apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: kafka-connect-cluster
  name: s3-source 
spec:
  class: org.apache.camel.kafkaconnector.aws2s3.CamelAws2s3SourceConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    topics: s3-topic
    camel.source.path.bucketNameOrArn: claim-check-8f3b492b-09b2-4eca-8373-27bb624ebb9e 
    camel.source.endpoint.overrideEndpoint: true
    camel.source.endpoint.uriEndpointOverride: http://s3.openshift-storage.svc
    camel.source.maxPollDuration: 10000
    camel.component.aws2-s3.accessKey: ${file:/opt/kafka/external-configuration/aws-credentials/AWS_ACCESS_KEY_ID}
    camel.component.aws2-s3.secretKey: ${file:/opt/kafka/external-configuration/aws-credentials/AWS_SECRET_ACCESS_KEY}
    camel.component.aws2-s3.region: noobaa

